name: build-android-no-sign

on:
  workflow_dispatch:

env:
  GO_VERSION: "1.24"
  FLUTTER_VERSION: "3.24.5"
  JAVA_VERSION: "17"

permissions:
  contents: write

jobs:
  get-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Get latest release
        id: release
        uses: monkeyWie/get-latest-release@v2.1
        with:
          myToken: ${{ github.token }}

  build-android:
    runs-on: ubuntu-latest
    needs: get-release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build Go Mobile library
        env:
          VERSION: ${{ needs.get-release.outputs.version }}
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

          gomobile bind \
            -tags nosqlite \
            -ldflags "-w -s -checklinkname=0 -X github.com/GopeedLab/gopeed/pkg/base.Version=${VERSION}" \
            -target=android \
            -androidapi 21 \
            -javapkg com.gopeed \
            -o ui/flutter/android/app/libs/libgopeed.aar \
            github.com/alrufaaey-yahoo/gopeed/bind/mobile

      - name: Build APKs (unsigned)
        env:
          VERSION: ${{ needs.get-release.outputs.version }}
        run: |
          cd ui/flutter
          flutter pub get

          flutter build apk \
            --release \
            --dart-define=UPDATE_CHANNEL=androidApk

          flutter build apk \
            --release \
            --split-per-abi \
            --dart-define=UPDATE_CHANNEL=androidApk

          mkdir -p dist
          cp build/app/outputs/flutter-apk/app-release.apk dist/Gopeed-v${VERSION}-android-unsigned.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk dist/Gopeed-v${VERSION}-android-arm64-v8a-unsigned.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk dist/Gopeed-v${VERSION}-android-armeabi-v7a-unsigned.apk
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk dist/Gopeed-v${VERSION}-android-x86_64-unsigned.apk

      - name: Upload APKs
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.get-release.outputs.upload_url }}
          asset_path: ui/flutter/dist/*
          overwrite: true
